# Generated by Django 5.2.4 on 2025-12-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_emailverification_cascade_sql'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='user',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254, verbose_name='Email'),
        ),
    ]
